server:
  port: 8080
  
    
logging:
  level: 
    ROOT : DEBUG
    
feign:
  client:
    config:
      books:
        loopback:
          enabled: true
          url: /harry
          data: {"name":"Harry Potter","price":10000,"author":"J. K. Rowling"}