server:
  port: 8080
  
    
logging:
  level: 
    ROOT : DEBUG
    
#feign:
#  hystrix:
#    enabled: true
#
#hystrix:
#  command:
#    books:
#      execution:
#        isolation:
#          strategy: THREAD
#          thread:
#            timeoutInMillsecods: 1
